#targets:
#  $default:
#    builders:
#      drift_dev:
#        options:
#          databases:
#            # Required: A name for the database and it's path
#            my_database: lib/data/datasource/local/cache_response.dart